# SPDX-License-Identifier: MIT
"""Tests for canonical MEMH encoding and hashing.

These tests use temporary files only.  They do not depend on committed
``artifacts/`` payloads because those payloads are generated by the artifact
flow, not authored by the test layer.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from trecap_golden.artifacts.hashes import canonical_memh_file_hash, canonical_memh_hash, sha256_file
from trecap_golden.artifacts.memh import (
    MemhContract,
    MemhError,
    canonical_text,
    contract_for_kind,
    decode_token,
    encode_value,
    infer_contract,
    read_memh,
    write_memh,
)


def test_signed_sample_memh_roundtrip_and_canonical_hash(tmp_path: Path) -> None:
    contract = contract_for_kind("x_in", rows=4)
    values = (-2048, -1, 0, 2047)
    path = tmp_path / "x_in.memh"

    write_memh(path, values, contract)

    assert path.read_text(encoding="ascii") == "800\nfff\n000\n7ff\n"
    assert read_memh(path, contract).values == values
    assert canonical_memh_file_hash(path, contract) == canonical_memh_hash(values, contract)
    # For a canonical file, raw byte hash and logical canonical hash coincide.
    assert sha256_file(path) == canonical_memh_hash(values, contract)


def test_window_and_twiddle_endpoint_encodings() -> None:
    window = contract_for_kind("window_qw")
    twiddle = contract_for_kind("twiddle_re")

    assert encode_value(32768, window) == "8000"
    assert decode_token("8000", window) == 32768

    assert encode_value(32768, twiddle) == "08000"
    assert encode_value(-32768, twiddle) == "18000"
    assert encode_value(-1, twiddle) == "1ffff"
    assert decode_token("08000", twiddle) == 32768
    assert decode_token("18000", twiddle) == -32768
    assert decode_token("1ffff", twiddle) == -1


def test_infer_contract_for_standard_artifact_names() -> None:
    assert infer_contract("x_in.memh").width_bits == 12
    assert infer_contract("x_in.memh").signed is True
    assert infer_contract("y_out.memh").signed is True
    assert infer_contract("window_qw.memh").signed is False
    assert infer_contract("twiddle_inv_im.memh").width_bits == 17
    with pytest.raises(MemhError):
        infer_contract("random.memh")


@pytest.mark.parametrize(
    "payload",
    [
        b"800\r\n",  # CRLF
        b"800\n\n",  # blank line
        b"800",  # missing final LF
        b"ABC\n",  # uppercase
        b"0x800\n",  # prefix
        b" 800\n",  # leading space
    ],
)
def test_rejects_noncanonical_memh_text(tmp_path: Path, payload: bytes) -> None:
    path = tmp_path / "bad.memh"
    path.write_bytes(payload)
    with pytest.raises(MemhError):
        read_memh(path, contract_for_kind("x_in", rows=1))


def test_row_count_and_range_are_enforced(tmp_path: Path) -> None:
    path = tmp_path / "sample.memh"
    write_memh(path, [1, 2], MemhContract(width_bits=12, signed=True, rows=2))

    with pytest.raises(MemhError, match="expected 3 rows"):
        read_memh(path, MemhContract(width_bits=12, signed=True, rows=3))

    with pytest.raises(MemhError, match="does not fit"):
        canonical_text([2048], MemhContract(width_bits=12, signed=True, rows=1))

    with pytest.raises(MemhError, match="unsigned value"):
        canonical_text([-1], MemhContract(width_bits=16, signed=False, rows=1))
