#!/usr/bin/env python3
"""Resolve one DE1-SoC profile into actual FPGA parameters and HPS startup controls.

Generated numeric enums and packet masks remain owned by spec/generated. This
command prepares configuration only; it never invokes Quartus or starts hardware.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from check_profiles import (
    ProfileCheckError, effective_profile, load_contracts, load_json,
    resolve_cli_profile, validate_paths,
)


def resolve(root: Path, profile_name: str) -> dict:
    path = resolve_cli_profile(root, profile_name)
    contracts = load_contracts(root)
    profiles = validate_paths(root, [path], contracts)
    result = dict(effective_profile(root, profiles[path], path, contracts))
    if result["build"]["target"] != "de1soc_full":
        raise ProfileCheckError("runtime binding requires a DE1-SoC full-board profile")
    if not result["transport"]["hps_udp_enable"]:
        raise ProfileCheckError("runtime binding requires the HPS UDP transport")
    inputs = result["input"]
    params = {
        "STATUS_TICK_HZ": result["status_rate_hz"],
        "METRICS_TICK_HZ": result["metrics_rate_hz"],
        "AUDIO_LINEOUT_ALLOWED": int(inputs.get("audio", {}).get("lineout_enable", False)),
    }
    if inputs["kind"] == "bram_replay":
        vector = load_json(root / inputs["vector_config"])
        params.update({
            "SAMPLE_TICK_HZ": result["sample_rate_hz"],
            "SAMPLE_RATE_HZ": result["sample_rate_hz"],
            "REPLAY_X_MEMH_FILE": inputs["input_memh"],
            "REPLAY_MEM_DEPTH": vector["configuration"]["Ns"],
            "REPLAY_INPUT_SAMPLES": vector["configuration"]["Ns"],
        })
        threshold = str(vector["configuration"]["THR2"])
    else:
        threshold = str(load_json(root / "spec/generated/core_config.json")["configuration"]["THR2"])
    if inputs["kind"] == "audio_wrapper":
        audio = inputs["audio"]
        params.update({"AUDIO_SAMPLE_W": audio["codec_sample_width"],
                       "AUDIO_MCLK_HZ": audio["master_clock_hz"],
                       "SAMPLE_TICK_HZ": result["sample_rate_hz"],
                       "SAMPLE_RATE_HZ": result["sample_rate_hz"]})
    if inputs["kind"] == "adc_live":
        adc = inputs["adc"]
        params.update({"ADC_BITS": adc["sample_width_bits"],
                       "ADC_SAMPLE_RATE_HZ": adc["continuous_sample_rate_hz"],
                       "ADC_DEFAULT_CHANNEL": adc["default_channel"]})
    args = ["--source-mode", str(result["source_mode_value"]),
            "--sample-rate-hz", str(result["sample_rate_hz"]),
            "--packet-enable", result["packet_enable_mask"],
            "--spec-mode", str(result["spec_mode_value"]),
            "--spec-shift", str(result["spec_shift"]),
            "--wave-decim", str(result["wave_decim"]), "--thr2", threshold]
    if not result["transport"]["command_server_enable"]:
        args.append("--no-commands")
    result["fpga_top_parameters"] = params
    result["hps_startup_args"] = args
    result["hps_runtime_config"] = result["transport"]["hps_runtime_config"]
    result["binding_notes"] = [
        "FPGA always resets source mode to BRAM; HPS performs the selected source commit.",
        "Telemetry cadence is synthesized; use the same profile for FPGA build and HPS launch.",
        "BRAM replay starts through its board/control trigger, never automatically by profile selection.",
        "ADC manual conversion is board diagnostics only; continuous operation requires SW7 low.",
    ]
    return result


def tcl_string(value: str) -> str:
    for before, after in (("\\", "\\\\"), ('"', '\\"'), ("$", "\\$"), ("[", "\\["), ("]", "\\]")):
        value = value.replace(before, after)
    return '"' + value + '"'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", required=True)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--format", choices=("json", "hps-args", "hps-config", "qsf"), default="json")
    parser.add_argument("--output", type=Path)
    options = parser.parse_args()
    try:
        root = options.root.resolve()
        resolved = resolve(root, options.profile)
        if options.format == "hps-config":
            content = str((root / resolved["hps_runtime_config"]).resolve()) + "\n"
        elif options.format == "hps-args":
            # One token per line: consumed with bash readarray, never eval.
            content = "\n".join(resolved["hps_startup_args"]) + "\n"
        elif options.format == "qsf":
            lines = ["# Generated by resolve_runtime_profile.py; do not edit.",
                     "# Profile SHA-256: " + resolved["source_profile_sha256"]]
            for name, value in resolved["fpga_top_parameters"].items():
                if name == "REPLAY_X_MEMH_FILE":
                    # Quartus string parameters require the HDL quotes to survive Tcl parsing.
                    value = tcl_string('"' + (root / value).resolve().as_posix() + '"')
                else:
                    value = str(value)
                lines.append(f"set_parameter -name {name} {value}")
            content = "\n".join(lines) + "\n"
        else:
            content = json.dumps(resolved, indent=2, sort_keys=True) + "\n"
        if options.output:
            options.output.parent.mkdir(parents=True, exist_ok=True)
            options.output.write_text(content, encoding="utf-8", newline="\n")
        else:
            sys.stdout.write(content)
    except (ProfileCheckError, OSError, KeyError, ValueError) as exc:
        print(f"profile binding: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
