#!/usr/bin/env python3
"""Qualify the selected native SV simulator and fail-closed execution contract.

Only an immutable run directory receives logs, library state and captures.
Frozen inputs and production sources are never regenerated by this command.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import uuid

DIAGNOSTIC = re.compile(r"\*\*\s+(?:Error|Fatal):|ENV_(?:SETUP|INPUT_FILE|TRACE_OPEN|PACKAGE)_")
EXPECTED_TRACE = [
    "TRECAP_ENV_TRACE_V1",
    "payload fedcba9876543210 ffffffffffffff -32768",
    "accepts 2",
    "complete",
]


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def execute(argv: list[str], cwd: Path, log: Path, timeout: float = 60) -> dict:
    """Bound one owned process tree and retain all output before classification."""
    started = time.monotonic()
    flags = subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0
    timed_out = False
    with log.open("wb") as stream:
        proc = subprocess.Popen(argv, cwd=cwd, stdout=stream,
                                stderr=subprocess.STDOUT, creationflags=flags,
                                start_new_session=(os.name != "nt"))
        try:
            code = proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            timed_out = True
            if os.name == "nt":
                subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                               check=False, timeout=15)
            else:
                import signal
                os.killpg(proc.pid, signal.SIGKILL)
            proc.kill()
            code = proc.wait(timeout=15)
    return {"exit_code": code, "timed_out": timed_out,
            "duration_seconds": round(time.monotonic() - started, 3),
            "log": log.name, "log_sha256": digest(log),
            "text": log.read_text(encoding="utf-8", errors="replace")}


def validate_trace(path: Path) -> tuple[bool, str]:
    if not path.is_file():
        return False, "missing trace"
    try:
        rows = path.read_text(encoding="ascii").splitlines()
    except (OSError, UnicodeError) as exc:
        return False, type(exc).__name__
    if rows != EXPECTED_TRACE:
        return False, "trace identity/value/count/completion mismatch"
    return True, "exact trace"


def classify(result: dict, trace: Path) -> tuple[str, str]:
    if result["timed_out"]:
        return "TIMEOUT", "host watchdog"
    if "ENV_EXPECTED_CYCLE_WATCHDOG" in result["text"]:
        return "TIMEOUT", "simulation watchdog"
    if result["exit_code"] != 0 or DIAGNOSTIC.search(result["text"]):
        return "FAIL_DUT", "simulator diagnostic or failure exit"
    if "TRECAP_ENV_COMPLETED" not in result["text"]:
        return "FAIL_INFRASTRUCTURE", "missing completion event"
    good, why = validate_trace(trace)
    return ("PASS" if good else "FAIL_INFRASTRUCTURE"), why


def resolve_filelist(repo: Path, path: Path) -> tuple[list[str], list[Path]]:
    args, sources = [], []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("+incdir+"):
            args.append("+incdir+" + (repo / line[len("+incdir+"):]).as_posix())
        elif line.startswith("-f "):
            nested, listed = resolve_filelist(repo, repo / line[3:].strip())
            args.extend(nested)
            sources.extend(listed)
        elif line.startswith(("+", "-")):
            raise ValueError("Unreviewed filelist option: " + line)
        else:
            source = repo / line
            if not source.is_file():
                raise FileNotFoundError(line)
            args.append(source.as_posix())
            sources.append(source)
    return args, sources


def run(repo: Path, simulator_dir: Path, timeout: float) -> tuple[Path, dict]:
    identity = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:8]
    run_dir = repo / "runs" / "verification" / ("environment-" + identity)
    run_dir.mkdir(parents=True, exist_ok=False)
    tools = {name: simulator_dir / (name + (".exe" if os.name == "nt" else ""))
             for name in ("vlib", "vmap", "vlog", "vsim")}
    summary = {"schema_version": 1, "run_id": run_dir.name,
               "utc_start": datetime.now(timezone.utc).isoformat(),
               "scope": ["T-ENV-01", "T-ENV-02 partial: environment trace",
                         "T-ENV-03 partial: native runner"],
               "capabilities_excluded": ["concurrent assertions", "covergroups",
                                         "code coverage", "vendor models", "DPI"],
               "stages": [], "cases": [], "overall": "NOT_RUN"}
    local_identity = {"tool_paths": {k: str(v) for k, v in tools.items()},
                      "python": sys.executable, "repository": str(repo)}
    (run_dir / "local_environment.json").write_text(json.dumps(local_identity, indent=2) + "\n")
    try:
        for name, path in tools.items():
            if not path.is_file():
                raise FileNotFoundError("Required simulator tool: " + name)
        summary["tool_sha256"] = {k: digest(v) for k, v in tools.items()}
        result = execute([str(tools["vsim"]), "-version"], run_dir,
                         run_dir / "version.log", timeout)
        if result["exit_code"] or result["timed_out"]:
            raise RuntimeError("Simulator version query failed")
        summary["simulator_version"] = result["text"].strip()
        args, sources = resolve_filelist(repo, repo / "filelists/rtl_core_plus_fft.f")
        probe = repo / "sim/verification/environment_probe.sv"
        sources += [probe, repo / "filelists/rtl_core_plus_fft.f", Path(__file__).resolve()]
        summary["source_sha256"] = {p.relative_to(repo).as_posix(): digest(p)
                                    for p in sources}
        summary["defines"] = []
        summary["compile_options"] = ["-sv", "-warning", "2892", "-work", "work"]
        summary["diagnostic_policy"] = {"2892": "Retain as warning: ANSI input logic under default_nettype none; see installed verror 2892. No assertion diagnostics disabled."}
        setup = [
            ("create-library", [str(tools["vlib"]), "work"]),
            ("local-configuration", [str(tools["vmap"]), "-c"]),
            ("compile", [str(tools["vlog"]), "-sv", "-warning", "2892", "-work", "work", *args, probe.as_posix()]),
        ]
        for label, command in setup:
            result = execute(command, run_dir, run_dir / (label + ".log"), timeout)
            summary["stages"].append({"stage": label, **{k: v for k, v in result.items() if k != "text"}})
            if result["exit_code"] != 0 or result["timed_out"] or DIAGNOSTIC.search(result["text"]):
                raise RuntimeError("Setup failed: " + label)
        fixture = run_dir / "probe_input.hex"
        fixture.write_bytes(b"fedcba9876543210\n8000000000000001\n")
        modes = {
            "positive": ("PASS", None),
            "assert": ("FAIL_DUT", "ENV_EXPECTED_ASSERT"),
            "error": ("FAIL_DUT", "ENV_EXPECTED_ERROR"),
            "fatal": ("FAIL_DUT", "ENV_EXPECTED_FATAL"),
            "x": ("FAIL_DUT", "ENV_EXPECTED_X_REJECT"),
            "z": ("FAIL_DUT", "ENV_EXPECTED_Z_REJECT"),
            "sim_timeout": ("TIMEOUT", "ENV_EXPECTED_CYCLE_WATCHDOG"),
            "missing_completion": ("FAIL_INFRASTRUCTURE", None),
            "host_timeout": ("TIMEOUT", None),
        }
        run_do = run_dir / "run.do"
        run_do.write_text("onerror {quit -code 2}\nrun -all\nquit -code 0\n", encoding="ascii")
        for mode, (expected, marker) in modes.items():
            capture = run_dir / (mode + ".trace")
            command = [str(tools["vsim"]), "-c", "-onfinish", "stop",
                       "-voptargs=+acc", "work.verification_environment_probe",
                       "+MODE=" + mode, "+TRACE=" + capture.as_posix(),
                       "+INPUT=" + fixture.as_posix(), "-do",
                       run_do.as_posix()]
            result = execute(command, run_dir, run_dir / (mode + ".log"),
                             8 if mode == "host_timeout" else timeout)
            observed, reason = classify(result, capture)
            marker_ok = marker is None or marker in result["text"]
            passed = observed == expected and marker_ok
            summary["cases"].append({"case": mode, "expected_observation": expected,
                                     "observed": observed, "reason": reason,
                                     "expected_marker_present": marker_ok,
                                     "qualification": "PASS" if passed else "FAIL",
                                     **{k: v for k, v in result.items() if k != "text"}})
        # Mutation witnesses exercise the trace validator independently of simulation.
        mutation_dir = run_dir / "checker_mutations"
        mutation_dir.mkdir()
        for name, content in {
            "empty": "", "truncated": "\n".join(EXPECTED_TRACE[:-1]) + "\n",
            "wrong_value": "\n".join(EXPECTED_TRACE).replace("-32768", "32768") + "\n",
            "wrong_count": "\n".join(EXPECTED_TRACE).replace("accepts 2", "accepts 1") + "\n",
            "duplicate": "\n".join(EXPECTED_TRACE + ["complete"]) + "\n",
        }.items():
            path = mutation_dir / (name + ".trace")
            path.write_text(content, encoding="ascii")
            accepted, reason = validate_trace(path)
            summary["cases"].append({"case": "trace_" + name, "observed": reason,
                                     "qualification": "FAIL" if accepted else "PASS"})
        accepted, reason = validate_trace(mutation_dir / "missing.trace")
        summary["cases"].append({"case": "trace_missing", "observed": reason,
                                 "qualification": "FAIL" if accepted else "PASS"})
        summary["overall"] = "PASS" if all(c["qualification"] == "PASS" for c in summary["cases"]) else "FAIL_INFRASTRUCTURE"
    except (OSError, ValueError, RuntimeError) as exc:
        summary["overall"] = "BLOCKED_CAPABILITY"
        summary["failure"] = str(exc)
    summary["utc_end"] = datetime.now(timezone.utc).isoformat()
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return run_dir, summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--simulator-dir", type=Path)
    parser.add_argument("--timeout", type=float, default=90)
    options = parser.parse_args()
    found = shutil.which("vsim")
    simulator = options.simulator_dir or (Path(found).parent if found else None)
    if simulator is None:
        parser.error("vsim is not on PATH; pass --simulator-dir")
    path, summary = run(options.repo.resolve(), simulator.resolve(), options.timeout)
    print(json.dumps({"run": path.relative_to(options.repo.resolve()).as_posix(),
                      "overall": summary["overall"],
                      "cases": len(summary["cases"]),
                      "failure": summary.get("failure")}, indent=2))
    return 0 if summary["overall"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
