#!/usr/bin/env python3
"""Generate reference-model C++ and Python constants from the checked-in core contract.

This emits source bindings only. It never writes coefficient, input, result, or
release artifacts. The package's spec/generated/core_config.json is a synchronized
source for the reference arithmetic bindings and the integrated project snapshot.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_contract(path: Path):
    data = json.loads(path.read_text(encoding="utf-8"),
                      object_pairs_hook=unique_object,
                      parse_constant=lambda value: (_ for _ in ()).throw(ValueError(value)))
    if data["schema"] != "trecap_phase2_core_config_v1":
        raise ValueError("unsupported core contract schema")
    cfg, widths = data["configuration"], data["widths"]
    for key in ("N", "L", "P", "H", "F", "G", "D", "PROTECT_DC", "PROTECT_NYQ"):
        if type(cfg[key]) is not int or cfg[key] < 0:
            raise ValueError(f"{key} must be a nonnegative integer")
    n, length, p, h, f, g, d = (cfg[key] for key in ("N", "L", "P", "H", "F", "G", "D"))
    if not (0 < n <= 62 and 0 < f <= 30 and 0 < p < 32 and
            length == 1 << p and h == length // 2 and d == length + g):
        raise ValueError("inconsistent core geometry")
    if cfg["PROTECT_DC"] not in (0, 1) or cfg["PROTECT_NYQ"] not in (0, 1):
        raise ValueError("protection flags must be 0 or 1")
    expected = dict(W_Qw=f+1, W_tw=f+2, W_u=n+f, W_fft=n+f+1,
                    W_fft_pre=n+f+2, W_can_pre=n+f+2, W_can=n+f+1,
                    W_mag2=2*(n+f+1), W_ifft=n+f+1+p,
                    W_z=n+f+1+p, W_ola=n+f+2+p)
    if widths != expected or any(type(v) is not int for v in widths.values()):
        raise ValueError("width schedule does not match the core formulas")
    if max(expected.values()) > 64 or expected["W_ifft"] + expected["W_tw"] + 1 > 63:
        raise ValueError("configuration exceeds the reference model int64 arithmetic domain")
    threshold = cfg["THR2"]
    if not isinstance(threshold, str) or not threshold.isascii() or not threshold.isdecimal() or str(int(threshold)) != threshold:
        raise ValueError("THR2 must be a canonical unsigned decimal string")
    if int(threshold) >= 1 << expected["W_mag2"]:
        raise ValueError("THR2 outside magnitude-squared width")
    return data


def emit(data):
    cfg = data["configuration"]
    values = {key: cfg[key] for key in ("N", "L", "P", "H", "F", "G", "D")}
    values.update(PROTECT_DC_DEFAULT=cfg["PROTECT_DC"], PROTECT_NYQ_DEFAULT=cfg["PROTECT_NYQ"],
                  THR2_DEFAULT=cfg["THR2"], SCHEMA=data["schema"],
                  SPEC_REVISION=data["spec_revision"], TELEMETRY_REVISION=data["telemetry_revision"])
    names = {"fft_mode": "FFT_MODE", "rounding_mode": "ROUNDING_MODE",
             "tail_policy": "TAIL_POLICY", "threshold_mapping": "THRESHOLD_MAPPING"}
    values.update({names[key]: value for key, value in data["contract"].items()})
    values.update(MEMH_ENCODING=data["artifact_contract"]["memh_encoding"],
                  HASH_RULE=data["artifact_contract"]["hash_rule"])
    values.update(data["widths"])
    py = '# SPDX-License-Identifier: MIT\n# Generated by scripts/gen_config.py; do not edit.\n\n'
    py += "\n".join(f"{key} = {value!r}" for key, value in values.items()) + "\n"
    py += f"\nSOURCE_MODES = {data['source_modes']!r}\n"
    cpp = '// SPDX-License-Identifier: MIT\n// Generated by scripts/gen_config.py; do not edit.\n#pragma once\n\n#include <string_view>\n\nnamespace trecap::reference_config {\n'
    for key, value in values.items():
        if isinstance(value, int):
            cpp += f"inline constexpr unsigned {key} = {value}U;\n"
        else:
            cpp += f"inline constexpr std::string_view {key} = {json.dumps(value)};\n"
    cpp += "}  // namespace trecap::reference_config\n"
    return {
        ROOT / "python/trecap_golden/generated/_core_constants.py": py,
        ROOT / "include/trecap_golden/generated/core_config.hpp": cpp,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "spec/generated/core_config.json")
    args = parser.parse_args()
    for path, text in emit(load_contract(args.config)).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
