`timescale 1ns/1ps
`default_nettype none

// Arizona State University 
// Capstone Senior Project
// Sigma Force
// Dat Dinh, Dat Huynh, Paul Applebee, Kyung Jae Son
// io_monitor.sv
//
// Fully functional monitor/checker for the *board I/O* of t_recap_demo_top.
//
// Verifies that the external outputs (LEDR + HEX0..HEX5) correctly reflect
// the internal debug/LED latches that update on dbg_tick.
//
// DUT behavior (from t_recap_demo_top.sv):
//   - ledr_lat <= {alive, suppressed_last, thresh_used[7:0]} on dbg_tick
//   - dbg_word_lat <= dbg_word on dbg_tick
//   - LEDR is assigned to ledr_lat
//   - HEX0..HEX5 show dbg_word_lat as 6 hex digits using hex7seg
//
// IMPORTANT timing detail:
//   dbg_tick is generated by tick_pulse_gen (registered). Because it is a
//   flop output, other always_ff blocks react to dbg_tick=1 on the *following*
//   posedge when dbg_tick is high coming into that edge.
//
// This monitor models that:
//   - At each posedge, read pre-NBA values and compute what the latches
//     should become after NBA updates.
//   - After #0 (post-NBA), check taps + board outputs vs expected.
//
// Plusargs:
//   +IO_MON_DISABLE              : disable
//   +IO_MON_VERBOSE              : verbose prints
//   +IO_MON_MAX_ERR=<N>          : max errors before fatal (default 10; 0=never)
//   +IO_MON_STOP_ON_ERR          : fatal on first mismatch
//
//   +IO_MON_NO_CHECK_LEDR        : don't check LEDR
//   +IO_MON_NO_CHECK_HEX         : don't check HEX
//   +IO_MON_NO_CHECK_DBGWORD     : don't check dbg_word selection logic
//   +IO_MON_CHECK_STABILITY      : ensure LEDR/HEX only change on dbg_tick (default ON)
//   +IO_MON_NO_CHECK_STABILITY   : disable stability checking
//   +IO_MON_CHECK_BYPASS_THRESH  : if mode_sel==00, assert thresh_used==0
//
// Notes:
//   - Comparisons are done against *expected model state*, not against the
//     DUT's own dbg_word_lat/ledr_lat (though we also cross-check those).


module io_monitor #(
  parameter int N      = 12,
  parameter int LFSR_W = 16,
  parameter bit AUTO_START = 1'b1
) (
  board_if.tb              b,
  tap_if  t
);

  import tb_pkg::*;


  // Config

  bit disabled;
  bit verbose;
  int unsigned max_err;
  bit stop_on_err;

  bit check_ledr;
  bit check_hex;
  bit check_dbgword;
  bit check_stability;
  bit check_bypass_thresh;


  // Expected latched state (independent model)

  logic [9:0]  exp_ledr_lat;
  logic [23:0] exp_dbg_word_lat;

  // bookkeeping
  bit running;
  bit stop_req;
  int unsigned err_count;

  // last observed outputs (for stability checking)
  logic [9:0] last_ledr_obs;
  logic [6:0] last_hex_obs[0:5];
  bit last_outputs_valid;


  // Helpers

  function automatic logic [6:0] hex7seg_encode(input logic [3:0] hex);
    // active-low segments (matches DUT hex7seg module)
    begin
      unique case (hex)
        4'h0: hex7seg_encode = 7'b1000000;
        4'h1: hex7seg_encode = 7'b1111001;
        4'h2: hex7seg_encode = 7'b0100100;
        4'h3: hex7seg_encode = 7'b0110000;
        4'h4: hex7seg_encode = 7'b0011001;
        4'h5: hex7seg_encode = 7'b0010010;
        4'h6: hex7seg_encode = 7'b0000010;
        4'h7: hex7seg_encode = 7'b1111000;
        4'h8: hex7seg_encode = 7'b0000000;
        4'h9: hex7seg_encode = 7'b0010000;
        4'hA: hex7seg_encode = 7'b0001000;
        4'hB: hex7seg_encode = 7'b0000011;
        4'hC: hex7seg_encode = 7'b1000110;
        4'hD: hex7seg_encode = 7'b0100001;
        4'hE: hex7seg_encode = 7'b0000110;
        4'hF: hex7seg_encode = 7'b0001110;
        default: hex7seg_encode = 7'b1111111;
      endcase
    end
  endfunction

  function automatic logic [23:0] compute_dbg_word(
    input logic [1:0] mode_sel,
    input logic [31:0] suppressed_pairs,
    input logic [31:0] sum_abs_err,
    input logic [47:0] sum_sq_err
  );
    // Matches t_recap_demo_top:
    //   00: sum_abs_err
    //   01: suppressed_pairs
    //   10: sum_abs_err
    //   11: sum_sq_err[23:0]
    begin
      unique case (mode_sel)
        2'b00: compute_dbg_word = sum_abs_err[23:0];
        2'b01: compute_dbg_word = suppressed_pairs[23:0];
        2'b10: compute_dbg_word = sum_abs_err[23:0];
        default: compute_dbg_word = sum_sq_err[23:0];
      endcase
    end
  endfunction

  task automatic _fatal_or_count(input string msg);
    begin
      err_count++;
      $display("[io_monitor] ERROR[%0d] %s", err_count, msg);
      if (stop_on_err || (max_err != 0 && err_count >= max_err)) begin
        $fatal(1, "[io_monitor] Too many errors (err_count=%0d max_err=%0d)", err_count, max_err);
      end
    end
  endtask

  // Convenience: read HEX array into local array
  task automatic _snapshot_hex(output logic [6:0] hx[0:5]);
    begin
      hx[0] = b.HEX0;
      hx[1] = b.HEX1;
      hx[2] = b.HEX2;
      hx[3] = b.HEX3;
      hx[4] = b.HEX4;
      hx[5] = b.HEX5;
    end
  endtask


  // Public control

  task automatic start();
    if (running) begin
      $display("[io_monitor] NOTE: start() called but already running.");
      return;
    end
    stop_req = 1'b0;
    running  = 1'b1;
    fork
      run();
    join_none
  endtask

  task automatic stop();
    stop_req = 1'b1;
  endtask

  task automatic report(input string tag = "io_monitor");
    $display("[%s] errors=%0d exp_ledr=0x%0h exp_dbg_word_lat=0x%06h",
             tag, err_count, exp_ledr_lat, exp_dbg_word_lat);
  endtask


  // Init

  initial begin
    running = 1'b0;
    stop_req = 1'b0;
    err_count = 0;

    disabled = 1'b0;
    verbose  = 1'b0;
    max_err  = 10;
    stop_on_err = 1'b0;

    check_ledr   = 1'b1;
    check_hex    = 1'b1;
    check_dbgword= 1'b1;

    check_stability     = 1'b1;
    check_bypass_thresh = 1'b0;

    if ($test$plusargs("IO_MON_DISABLE")) disabled = 1'b1;
    if ($test$plusargs("IO_MON_VERBOSE")) verbose = 1'b1;

    void'($value$plusargs("IO_MON_MAX_ERR=%d", max_err));
    if ($test$plusargs("IO_MON_STOP_ON_ERR")) stop_on_err = 1'b1;

    if ($test$plusargs("IO_MON_NO_CHECK_LEDR")) check_ledr = 1'b0;
    if ($test$plusargs("IO_MON_NO_CHECK_HEX"))  check_hex  = 1'b0;
    if ($test$plusargs("IO_MON_NO_CHECK_DBGWORD")) check_dbgword = 1'b0;

    if ($test$plusargs("IO_MON_NO_CHECK_STABILITY")) check_stability = 1'b0;
    if ($test$plusargs("IO_MON_CHECK_STABILITY"))    check_stability = 1'b1;

    if ($test$plusargs("IO_MON_CHECK_BYPASS_THRESH")) check_bypass_thresh = 1'b1;

    // reset expected state
    exp_ledr_lat     = '0;
    exp_dbg_word_lat = '0;

    last_outputs_valid = 1'b0;

    if (disabled) begin
      $display("[io_monitor] Disabled via +IO_MON_DISABLE");
    end else begin
      $display("[io_monitor] Config: check_ledr=%0d check_hex=%0d check_dbgword=%0d check_stability=%0d check_bypass_thresh=%0d",
               check_ledr, check_hex, check_dbgword, check_stability, check_bypass_thresh);
      $display("[io_monitor] max_err=%0d stop_on_err=%0d verbose=%0d", max_err, stop_on_err, verbose);

      if (AUTO_START) start();
    end
  end


  // Async reset checker 

  always @(negedge t.rst_n) begin : async_rst_chk
    if (disabled) begin
      last_outputs_valid = 1'b0;
    end else begin

    // Model state resets immediately
    exp_ledr_lat     = '0;
    exp_dbg_word_lat = '0;

    // Let async reset propagate through continuous assigns / comb
    #0;

    if (check_ledr) begin
      if (^b.LEDR === 1'bX) begin
        _fatal_or_count("LEDR contains X during reset");
      end else if (b.LEDR !== 10'b0) begin
        _fatal_or_count($sformatf("LEDR not 0 during reset: got 0x%0h", b.LEDR));
      end
    end

    if (check_hex) begin
      logic [6:0] z;
      z = hex7seg_encode(4'h0);
      if ((^b.HEX0 === 1'bX) || (b.HEX0 !== z)) _fatal_or_count("HEX0 not showing 0 during reset");
      if ((^b.HEX1 === 1'bX) || (b.HEX1 !== z)) _fatal_or_count("HEX1 not showing 0 during reset");
      if ((^b.HEX2 === 1'bX) || (b.HEX2 !== z)) _fatal_or_count("HEX2 not showing 0 during reset");
      if ((^b.HEX3 === 1'bX) || (b.HEX3 !== z)) _fatal_or_count("HEX3 not showing 0 during reset");
      if ((^b.HEX4 === 1'bX) || (b.HEX4 !== z)) _fatal_or_count("HEX4 not showing 0 during reset");
      if ((^b.HEX5 === 1'bX) || (b.HEX5 !== z)) _fatal_or_count("HEX5 not showing 0 during reset");
    end

    last_outputs_valid = 1'b0;

    if (verbose) $display("[io_monitor] Observed async reset; expected/output state cleared.");
    end
  end


  // Main run loop

  task automatic run();
    logic [9:0]  exp_ledr_next;
    logic [23:0] exp_dbg_next;

    logic [23:0] dbg_word_pre;
    bit dbg_tick_pre;

    logic [3:0] nib[0:5];
    logic [6:0] exp_hex[0:5];
    logic [6:0] cur_hex[0:5];

    // for stability
    logic [9:0]  cur_ledr;

    begin
      // Wait for clock to become known
      wait (^t.clk !== 1'bX);

      forever begin
        @(posedge t.clk);

        dbg_tick_pre = t.dbg_tick;

        if (stop_req) begin
          $display("[io_monitor] stop requested.");
          running = 1'b0;
          disable run;
        end

        // If in reset, we rely on async reset always block to set expected.
        if (!t.rst_n) begin
          // still snapshot outputs for stability baseline after reset releases
          last_outputs_valid = 1'b0;
          continue;
        end

        // Optional: bypass threshold invariant
        if (check_bypass_thresh) begin
          if (t.mode_sel == 2'b00) begin
            if (t.thresh_used !== '0) begin
              _fatal_or_count($sformatf("bypass invariant violated: mode_sel==00 but thresh_used=%0d", t.thresh_used));
            end
          end
        end

        // Compute expected dbg_word selection from *pre-NBA* metrics and mode
        if (check_dbgword) begin
          dbg_word_pre = compute_dbg_word(t.mode_sel, t.suppressed_pairs, t.sum_abs_err, t.sum_sq_err);
          if (^t.dbg_word !== 1'bX) begin
            if (t.dbg_word !== dbg_word_pre) begin
              _fatal_or_count($sformatf("dbg_word selection mismatch: dut dbg_word=0x%06h exp=0x%06h (mode=%0b)",
                                        t.dbg_word, dbg_word_pre, t.mode_sel));
            end
          end
        end else begin
          // Even if not checking, still compute to drive expected latch model
          dbg_word_pre = compute_dbg_word(t.mode_sel, t.suppressed_pairs, t.sum_abs_err, t.sum_sq_err);
        end

        // Latch-update model:
        // if dbg_tick is HIGH at this posedge, the latches update using the
        // current (pre-NBA) values.
        if (dbg_tick_pre) begin
          exp_dbg_next  = dbg_word_pre;
          exp_ledr_next = {t.alive, t.suppressed_last, t.thresh_used[7:0]};
        end else begin
          exp_dbg_next  = exp_dbg_word_lat;
          exp_ledr_next = exp_ledr_lat;
        end

        // Now wait for NBA updates (latches/metrics update) to land.
        #0;

        // Cross-check internal latches against expected model
        if (^t.dbg_word_lat === 1'bX) begin
          _fatal_or_count("dbg_word_lat contains X");
        end else if (t.dbg_word_lat !== exp_dbg_next) begin
          _fatal_or_count($sformatf("dbg_word_lat mismatch: dut=0x%06h exp=0x%06h (dbg_tick_pre=%0d mode=%0b)",
                                    t.dbg_word_lat, exp_dbg_next, dbg_tick_pre, t.mode_sel));
        end

        if (^t.ledr_lat === 1'bX) begin
          _fatal_or_count("ledr_lat contains X");
        end else if (t.ledr_lat !== exp_ledr_next) begin
          _fatal_or_count($sformatf("ledr_lat mismatch: dut=0x%0h exp=0x%0h (dbg_tick_pre=%0d)",
                                    t.ledr_lat, exp_ledr_next, dbg_tick_pre));
        end

        // External LEDR check
        if (check_ledr) begin
          if (^b.LEDR === 1'bX) begin
            _fatal_or_count("LEDR contains X");
          end else if (b.LEDR !== exp_ledr_next) begin
            _fatal_or_count($sformatf("LEDR mismatch: dut=0x%0h exp=0x%0h", b.LEDR, exp_ledr_next));
          end
        end

        // External HEX check
        if (check_hex) begin
          nib[0] = exp_dbg_next[3:0];
          nib[1] = exp_dbg_next[7:4];
          nib[2] = exp_dbg_next[11:8];
          nib[3] = exp_dbg_next[15:12];
          nib[4] = exp_dbg_next[19:16];
          nib[5] = exp_dbg_next[23:20];

          exp_hex[0] = hex7seg_encode(nib[0]);
          exp_hex[1] = hex7seg_encode(nib[1]);
          exp_hex[2] = hex7seg_encode(nib[2]);
          exp_hex[3] = hex7seg_encode(nib[3]);
          exp_hex[4] = hex7seg_encode(nib[4]);
          exp_hex[5] = hex7seg_encode(nib[5]);

          _snapshot_hex(cur_hex);

          if (^cur_hex[0] === 1'bX || cur_hex[0] !== exp_hex[0]) _fatal_or_count($sformatf("HEX0 mismatch: dut=%b exp=%b", cur_hex[0], exp_hex[0]));
          if (^cur_hex[1] === 1'bX || cur_hex[1] !== exp_hex[1]) _fatal_or_count($sformatf("HEX1 mismatch: dut=%b exp=%b", cur_hex[1], exp_hex[1]));
          if (^cur_hex[2] === 1'bX || cur_hex[2] !== exp_hex[2]) _fatal_or_count($sformatf("HEX2 mismatch: dut=%b exp=%b", cur_hex[2], exp_hex[2]));
          if (^cur_hex[3] === 1'bX || cur_hex[3] !== exp_hex[3]) _fatal_or_count($sformatf("HEX3 mismatch: dut=%b exp=%b", cur_hex[3], exp_hex[3]));
          if (^cur_hex[4] === 1'bX || cur_hex[4] !== exp_hex[4]) _fatal_or_count($sformatf("HEX4 mismatch: dut=%b exp=%b", cur_hex[4], exp_hex[4]));
          if (^cur_hex[5] === 1'bX || cur_hex[5] !== exp_hex[5]) _fatal_or_count($sformatf("HEX5 mismatch: dut=%b exp=%b", cur_hex[5], exp_hex[5]));
        end

        // Stability check: outputs should only change when dbg_tick was high at this posedge
        if (check_stability) begin
          cur_ledr = b.LEDR;
          _snapshot_hex(cur_hex);

          if (last_outputs_valid) begin
            if (!dbg_tick_pre) begin
              // No latch update expected => outputs must not change.
              if (check_ledr && (cur_ledr !== last_ledr_obs)) begin
                _fatal_or_count($sformatf("LEDR changed without dbg_tick: prev=0x%0h now=0x%0h", last_ledr_obs, cur_ledr));
              end
              if (check_hex) begin
                for (int i = 0; i < 6; i++) begin
                  if (cur_hex[i] !== last_hex_obs[i]) begin
                    _fatal_or_count($sformatf("HEX%0d changed without dbg_tick", i));
                  end
                end
              end
            end
          end

          // update stability baseline
          last_ledr_obs = cur_ledr;
          for (int i = 0; i < 6; i++) last_hex_obs[i] = cur_hex[i];
          last_outputs_valid = 1'b1;
        end

        // Commit expected state for next cycle
        exp_ledr_lat     = exp_ledr_next;
        exp_dbg_word_lat = exp_dbg_next;

        if (verbose && dbg_tick_pre) begin
          $display("[io_monitor] dbg_tick: LEDR<=0x%0h dbg_word_lat<=0x%06h (mode=%0b)",
                   exp_ledr_lat, exp_dbg_word_lat, t.mode_sel);
        end
      end
    end
  endtask

endmodule : io_monitor

`default_nettype wire




